experimental_monorepo_root = true

[tools]
node = "25"
ruby = "3.2"

"npm:@herb-tools/formatter" = "latest"
"npm:@herb-tools/linter" = "latest"
pnpm = "latest"

[monorepo]
config_roots = ["apps/demo"]

[env]
MISE_EXPERIMENTAL = 1
_.path = ['{{config_root}}/node_modules/.bin'] # add node modules binaries to the PATH so `npx` isn't needed

[tasks.setup]
description = "Run setup scripts for all packages"
run = "mise //apps/demo:setup"

[tasks.demo]
description = "Start the demo app"
run = "mise //apps/demo:dev"
