source "https://rubygems.org"

gem "rails", "~> 8.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false

group :development, :test do
  gem "pretty_please"
  gem "puts_debuggerer"

  gem "lookbooklet", path: "../../../booklet"
  gem "lookbook", path: "../../gems/lookbook"
end

group :development do
  gem "vite_rails"
  gem "listen"
  gem "web-console"
end
