[env]
PORT = "{{env.DOCS_PORT | default(value=8888)}}"

[tasks.setup]
description = "Install dependencies and initial setup tasks"
run = "bin/setup --skip-server"

[tasks.rails]
description = "Start the Rails server"
run = "bin/rails server"

[tasks.vite]
description = "Start the Vite server"
run = "bin/vite dev"

[tasks.start]
description = "Start the dev server(s)"
run = "pitchfork start rails vite lookbook"

[tasks.stop]
description = "Stop the dev server(s)"
run = "pitchfork stop rails vite lookbook"

[shell_alias]
dev = "mise start"
stop = "mise stop"
tui = "pitchfork tui"
