[tasks.setup]
description = "Install dependencies and initial setup tasks"
run = "bin/setup --skip-server"

[tasks.start]
description = "Start the development server"
run = "bin/dev"

[tasks."restart"]
description = "Restart all processes"
run = "bundle exec overmind restart"

[tasks."restart:web"]
description = "Restart the Rails server"
run = "bundle exec overmind restart web"

[tasks."restart:vite"]
description = "Restart the Vite dev server"
run = "bundle exec overmind restart vite"

[tasks.server]
description = "Start the Rails server (without Vite dev server)"
run = "bin/rails server"

[tasks.console]
description = "Start the Rails console"
run = "bin/rails console"
