[env]
PORT = "{{env.DOCS_PORT | default(value=8888)}}"

[tasks.setup]
description = "Install dependencies and initial setup tasks"
run = "bundle install --prefer-local && npm install"

[tasks.rails]
description = "Start the Rails server"
run = "bin/rails server"

[tasks.vite]
description = "Start the Vite server"
run = "bin/vite dev"

[tasks.start]
description = "Start the dev servers"
run = "pitchfork start rails vite lookbook"

[tasks.stop]
description = "Stop the dev servers"
run = "pitchfork stop rails vite lookbook"

[tasks.restart]
description = "Restart the dev servers"
run = "pitchfork restart rails vite lookbook"

[shell_alias]
dev = "mise start"
restart = "mise restart"
stop = "mise stop"
tui = "pitchfork tui"
