source "https://gem.coop"

gemspec

group :development, :test do
  gem "puts_debuggerer"
  gem "pretty_please"

  gem "view_component"
  gem "phlex"
end

group :test do
  gem "minitest"
  gem "minitest-reporters"
  gem "shoulda-context"
  gem "simplecov", require: false
end
