[tasks.setup]
description = "Install dependencies"
run = "bundle install --prefer-local && npm install"

[tasks."assets:build"]
description = "Build assets"
run = "npx vite build"

[tasks."assets:watch"]
description = "Watch assets and rebuild on change"
run = "npx vite build --watch"

[shell_alias]
build = "mise assets:build"
watch = "mise assets:watch"
