[env]
_.path = ['{{config_root}}/node_modules/.bin'] # add node modules binaries to the PATH so `npx` isn't needed

[tasks.setup]
description = "Install dependencies"
run = "bundle install --prefer-local && npm install"

[tasks."assets:build"]
description = "Build assets"
run = "npx vite build"

[tasks."assets:watch"]
description = "Watch assets and rebuild on change"
run = "mise watch assets:build -w app/frontend/lookbook"

[shell_alias]
build = "mise assets:build"
watch = "mise assets:watch"
