source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.1.2"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Use Vite.js for asset management [https://vite-ruby.netlify.app/]
gem "vite_rails"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

gem "view_component"

group :development, :test do
  gem "pretty_please"
  gem "puts_debuggerer"

  gem "lookbooklet", path: "../../../booklet"
  gem "lookbook", path: "../../gems/lookbook"
end

group :development do
  gem "listen"

  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
  # Process manager for Procfile-based applications [https://github.com/DarthSim/overmind]
  gem "overmind"
end
