[tasks.setup]
description = "Install dependencies and initial setup tasks"
run = "bin/setup --skip-server"

[tasks.start]
description = "Start the development server"
run = "bin/dev"

[tasks."restart"]
description = "Restart all processes"
run = "bundle exec overmind restart"

[tasks."restart:web"]
description = "Restart the Rails server"
run = "bundle exec overmind restart web"

[tasks."restart:js"]
description = "Restart the JS build watcher"
run = "bundle exec overmind restart js"

[tasks."restart:css"]
description = "Restart the CSS build watcher"
run = "bundle exec overmind restart css"

[tasks.server]
description = "Start the Rails server (without JS/CSS watchers)"
run = "bin/rails server"

[tasks.console]
description = "Start the Rails console"
run = "bin/rails console"
