[env]
PORT = "{{env.DEV_PORT | default(value=4444)}}"

[tasks.setup]
description = "Install dependencies and initial setup tasks"
run = "bundle install --prefer-local && npm install"

[tasks.rails]
description = "Start the Rails server"
run = "bin/rails server"

[tasks.vite]
description = "Start the Vite server"
run = "npx vite"

[tasks.start]
description = "Start the dev servers"
run = "pitchfork start lookbook rails vite"

[tasks.stop]
description = "Stop the dev servers"
run = "pitchfork stop lookbook rails vite"

[tasks.restart]
description = "Restart the dev servers"
run = "pitchfork restart lookbook rails vite"

[shell_alias]
dev = "mise start"
restart = "mise restart"
stop = "mise stop"
tui = "pitchfork tui"
