source "https://gem.coop"

gemspec

gem "puts_debuggerer"
gem "pretty_please"

gem "view_component"
gem "phlex"

group :test do
  gem "minitest"
  gem "minitest-reporters"
  gem "shoulda-context"
  gem "simplecov", require: false
end
