name: CI (minitest)

on:
  push:
    branches: [improve-dev-setup]

jobs:
  test:
    name: test (${{ matrix.rails_version }}, ${{ matrix.ruby_version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby_version: "3.0"
            rails_version: "6.1"
          - ruby_version: "3.1"
            rails_version: "7.0"
          - ruby_version: "3.2"
            rails_version: "7.1"
          - ruby_version: "3.3"
            rails_version: "7.2"
          - ruby_version: "3.3"
            rails_version: "8.0"
          - ruby_version: "3.4"
            rails_version: "8.0"
    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails_version }}.gemfile
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby ${{ matrix.ruby_version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Set system gem command
        run: gem update --system 3.5.23

      - name: Install bundler
        run: gem install bundler

      - name: Bundle for Appraisal
        run: bundle

      - name: Build and test
        run: |
          bundle exec appraisal rails-${{ matrix.rails_version }} bundle
          bundle exec appraisal rails-${{ matrix.rails_version }} rake test
        env:
          RAILS_VERSION: ${{ matrix.rails_version }}
          RUBY_VERSION: ${{ matrix.ruby_version }}
